create table SUBHAHINI_STATION_NAME(ID int PRIMARY KEY(ID), STATION_NAME varchar(80))


insert into SUBHAHINI_STATION_NAME values (1,'Central')
insert into SUBHAHINI_STATION_NAME values (2,'Egmore')
insert into SUBHAHINI_STATION_NAME values (3,'Nugabakam ')
insert into SUBHAHINI_STATION_NAME values (4,'St.thomas mount')
insert into SUBHAHINI_STATION_NAME values (5,'Tambaram')

create table SUBHASHINI_JOURNEY_DISTINATIONS
(STARTING_POINT int foreign key references  SUBHAHINI_STATION_NAME (ID),
ENDING_POINT int foreign key references SUBHAHINI_STATION_NAME(ID),DISTANCE int )
drop table SUBHASHINI_JOURNEY_DISTINATIONS
sp_rename 'JOURNEY_DISTINATIONS' ,'SUBHASHINI_JOURNEY_DISTINATIONS';
create table SUBHA_JOURNEY_DISTINATION
(STARTING_POINT int foreign key references  SUBHAHINI_STATION_NAME (ID),
ENDING_POINT int foreign key references SUBHAHINI_STATION_NAME(ID),DISTANCE int )

alter table SUBHA_JOURNEY_DISTINATION add REACHING_TIMING varchar(20);

insert into SUBHA_JOURNEY_DISTINATION values (1,2,10,0)
update SUBHA_JOURNEY_DISTINATION set DISTANCE=120 where STARTING_POINT=1
insert into SUBHA_JOURNEY_DISTINATION values (2,3,10,0)
update SUBHA_JOURNEY_DISTINATION set DISTANCE=120 where STARTING_POINT=2
insert into SUBHA_JOURNEY_DISTINATION values (3,4,10,0)
update SUBHA_JOURNEY_DISTINATION set DISTANCE=120 where STARTING_POINT=3
insert into SUBHA_JOURNEY_DISTINATION values (4,5,10,0)
update SUBHA_JOURNEY_DISTINATION set DISTANCE=120 where STARTING_POINT=4
select * from  SUBHA_JOURNEY_DISTINATION 

sp_rename 'CAL_TIME_DURATION' ,'SUBHASHINI_CAL_TIME_DURATION';
alter procedure SUBHASHINI_CAL_TIME_DURATION

@SPEED int  
as
begin
select * from SUBHA_JOURNEY_DISTINATION 
update  SUBHA_JOURNEY_DISTINATION set REACHING_TIMING=(DISTANCE/@SPEED)
where   REACHING_TIMING ='0'
end
exec SUBHASHINI_CAL_TIME_DURATION '80'
select * from SUBHAHINI_STATION_NAME
select SUBHAHINI_STATION_NAME.STATION_NAME,SUBHA_JOURNEY_DISTINATION.STARTING_POINT,SUBHA_JOURNEY_DISTINATION.ENDING_POINT from SUBHAHINI_STATION_NAME
inner join SUBHA_JOURNEY_DISTINATION on SUBHAHINI_STATION_NAME.ID=SUBHA_JOURNEY_DISTINATION.STARTING_POINT